service: lambda-jaxrs-cdi

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: demo
  region: eu-central-1
  memorySize: 512
  timeout: 20
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}

package:
  artifact: target/lambda-jaxrs-cdi.jar

functions:
  api:
    handler: de.serverlessbuch.lambda.LambdaHandler
    events:
      - http:
          path: /{proxy+}
          method: any
          private: true
